/**
 * Name: Wei Wang
 * Course: CS-665 Software Designs & Patterns
 * Date: 10/05/2024
 * File Name: GameController.java
 * Description: This class is responsible for the methods and attributes of the GameController.java.
 */

package edu.bu.met.cs665.state;

import java.util.List;

import edu.bu.met.cs665.mode.Mode;
import edu.bu.met.cs665.path.Path;
import edu.bu.met.cs665.path.Step;

/**
 * This is the GameController class implements Mode interface to realize Delegation Pattern.
 * This class is responsible for representing a GameController.
 * 
 * Ref: https://java-design-patterns.com/patterns/delegation/#programmatic-example-of-delegation-pattern-in-java
 */
public class GameController implements Mode {

  private final Mode mode;

  /**
   * Create the GameController object.
   * 
   * @param mode Crate the GameController with the given game mode
   */
  public GameController(Mode mode) {
    this.mode = mode;
  }

  /**
   * Validate the user-selected path against the game-generated one based on the different modes of the game.
   * 
   * @param gamePath The random path generated by the game
   * @param userPath The user input path
   * @return Return true if the user input path is the same as the game generated
   */
  @Override
  public boolean validatePath(Path gamePath, Path userPath) {
    List<Step> gameSteps = gamePath.getSteps();
    List<Step> userSteps = userPath.getSteps();

    if (gameSteps.size() != userSteps.size()) {
      return false;
    }

    return mode.validatePath(gamePath, userPath);
  }

}
