/**
 * Name: Wei Wang
 * Course: CS-665 Software Designs & Patterns
 * Date: 10/05/2024
 * File Name: EasyMode.java
 * Description: This class is responsible for the methods and attributes of the EasyMode.
 */
package edu.bu.met.cs665.mode;

import java.util.List;

import edu.bu.met.cs665.path.Path;
import edu.bu.met.cs665.path.Step;

/**
 * This is the DifficultMode class.
 * This class is responsible for representing a DifficultMode.
 */
public class EasyMode implements Mode {

  /**
   * Validate the path in easy mode. Only verify the directions.
   * 
   * @param gamePath The random path generated by the game
   * @param userPath The user input path
   * @return Return true if the user input path is the same as the game generated
   */
  @Override
  public boolean validatePath(Path gamePath, Path userPath) {

    List<Step> gameSteps = gamePath.getSteps();
    List<Step> userSteps = userPath.getSteps();

    // for (Step step : gameSteps) {
    // System.out.println("gamePath -> Color: " + step.getColor() + " Direction: " +
    // step.getDirection() + " Location: "
    // + step.getLocation().getX() + "," + step.getLocation().getY());
    // }

    // for (Step step : userSteps) {
    // System.out.println("userPath -> Color: " + step.getColor() + " Direction: " +
    // step.getDirection() + " Location: "
    // + step.getLocation().getX() + "," + step.getLocation().getY());
    // }

    for (int i = 0; i < gameSteps.size(); i++) {
      if (!gameSteps.get(i).getDirection().equals(userSteps.get(i).getDirection())) {
        return false;
      }
    }

    return true;
  }

}
